version: '3.9'
services:
  frontend:
    container_name: front-end
    build: ./front-end
    ports:
      - 3000:3000
    working_dir: /front-end
    volumes: 
      - ./front-end:/front-end
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:3000"] 
      timeout: 10s
      retries: 5
  backend:
    container_name: back-end
    build: ./back-end
    ports:
      - 2122:2122
    working_dir: /back-end
    volumes: 
      - ./back-end:/back-end
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "lsof", "-t", "-i:2122"] 
      timeout: 10s
      retries: 5
    networks:
      - api_db
  db:
    image: mysql
    container_name: database
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=facilita_system
      - MYSQL_PASSWORD=root
    restart: 'always'
    expose:
      - 3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
    networks:
      - api_db
networks:
  api_db:
    driver: bridge
